#!/bin/bash
rootPartition="vda1"
swapPartition="vda2"
efiPartition="vda3"
windiowManager="" # like i3wm and dwm
displayManager="" # like sddm
installPackages="base base-devel linux linux-firmware git vim neovim neofetch 
                 xorg xorg-xprop xorg-xset sudo firefox man-db man-pages" # This Packages You Want To Install
host=""

loadkeys us
cfdisk

mkfs.ext4 /dev/$rootPartition
mkswap /dev/$swapPartition
mkfs.fat -F 32 /dev/$efiPartition

mount /dev/$rootPartition /mnt
mount --mkdir /dev/$efiPartition /mnt/boot
swapon /dev/$swapPartition

pacstrap -K /mnt $installPackages $windiowManager $displayManager
genfstab -U /mnt >>/mnt/etc/fstab
ln -sf /usr/share/zoneinfo/UTC /mnt/etc/localtime

echo LANG=en_US.UTF-8 >>/mnt/etc/locale.conf
echo $host >>/mnt/etc/hostname

echo Changing The Root To /mnt
arch-chroot /mnt

mkinitcpio -P
passwd

grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
