#!/bin/bash

loadkeys us

lsblk
read -p "Disk: " disk

parted -s /dev/$disk mklabel gpt
parted -s /dev/$disk mkpart primary fat32 1MiB 1025MiB
parted -s /dev/$disk set 1 esp on
parted -s /dev/$disk mkpart primary ext4 1025MiB 100%

mkfs.fat -F 32 /dev/${disk}1
mkfs.ext4 /dev/${disk}2

mount /dev/${disk}2 /mnt
mount --mkdir /dev/${disk}1 /mnt/boot

pacstrap -K /mnt base base-devel linux linux-firmware git vim neovim neofetch \
          xorg xorg-xprop xorg-xset sudo firefox man-db man-pages grub efibootmgr networkmanager

genfstab -U /mnt >> /mnt/etc/fstab
ln -sf /usr/share/zoneinfo/UTC /mnt/etc/localtime
echo "LANG=en_US.UTF-8" >> /mnt/etc/locale.conf
echo "en_US.UTF-8 UTF-8" >> /mnt/etc/locale.gen
arch-chroot /mnt locale-gen

read -p "hostname: " hostname
echo "$hostname" >> /mnt/etc/hostname

arch-chroot /mnt passwd

read -p "username: " username
arch-chroot /mnt useradd -m -G wheel -s /bin/bash "$username"
arch-chroot /mnt passwd "$username"

arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

arch-chroot /mnt systemctl enable NetworkManager

read -p "display manager (sddm,lightdm): " displayManager

if [ "$displayManager" == "sddm" ]; then
    arch-chroot /mnt pacman -S --noconfirm sddm
elif [ "$displayManager" == "lightdm" ]; then
    arch-chroot /mnt pacman -S --noconfirm lightdm lightdm-gtk-greeter
elif [ "$displayManager" == "i3" ]; then
    arch-chroot /mnt pacman -S --noconfirm i3-wm i3status dmenu
fi

sudo pacman -S $displayManager $windowManager
arch-chroot /mnt systemctl enable $displayManager

echo "Made Arch Linux Discord:.t5a Reboot now!"
