#!/bin/bash
source install-script

mkinitcpio -P

echo -e "$STEP Root Password $ENDCOLORING"
passwd

echo -e "$STEP Username Password"
useradd -m -G users,audio,lp,optical,storage,video,wheel,power -s /bin/bash $username

mkdir /boot/efi

grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg

echo -e "$WARNING Remove \"last\" file, because you dont need it $ENDCOLORING"
